server:
  port: 80
zuul:
  routes:
    boards:
      path: /api/boards/**
      serviceId: boards
      url: http://koobz-board:8080/boards
      stripPrefix: true
    web:
      path: /**
      url: http://koobz-web:9000

---

spring:
  profiles: development
server:
  port: 8081
zuul:
  routes:
    boards:
      path: /api/boards/**
      serviceId: boards
      url: http://localhost:8080/boards
      stripPrefix: true
    web:
      path: /**
      url: http://localhost:9000

